version: '3.8'

x-models:
  warp10: &warp10
    build:
      context: .
      dockerfile: ./images/warp10/Dockerfile
    volumes: [ $PWD/warpscript:/usr/local/share/warpscript ]

  warp10_env: &warp10_env
    ENABLE_WARPSTUDIO: 'true'
    ENABLE_SENSISION: 'true'
    warpscript.repository.refresh: 1000
    warpscript.maxops: 1000000000
    warpscript.maxops.hard: 1000000000
    warpscript.maxfetch: 1000000000
    warpscript.maxfetch.hard: 1000000000
    warpscript.extension.debug: io.warp10.script.ext.debug.DebugWarpScriptExtension
    warpscript.maxrecursion: 1000
    warpscript.repository.directory: /usr/local/share/warpscript
    warpscript.extension.logEvent: io.warp10.script.ext.logging.LoggingWarpScriptExtension

  redis: &redis
      build:
        context: .
        dockerfile: ./images/redis/Dockerfile

services:
  redis-0:
    image: redis:6
    command: redis-server --port 6379 --slave-announce-ip "${EXTERNAL_HOST}"
    ports:
      - 6379:6379
    environment:
      - HOST_IP="${EXTERNAL_HOST}"

  redis-1:
    image: redis:6
    command: redis-server --port 6380 --slaveof "${EXTERNAL_HOST}" 6379 --slave-announce-ip "${EXTERNAL_HOST}"
    ports:
       - 6380:6380
    environment:
      - HOST_IP="${EXTERNAL_HOST}"

  redis-sentinel-0:
    image: redis:6
    command: |-
      bash -c 'cat > /tmp/sentinel.conf <<EOF
      port 16379
      logfile ""
      dir /tmp
      sentinel announce-ip ${EXTERNAL_HOST}
      sentinel announce-port 16379
      sentinel monitor scality-s3 "${EXTERNAL_HOST}" 6379 1
      EOF
      redis-sentinel /tmp/sentinel.conf'

    environment:
      - HOST_IP="${EXTERNAL_HOST}"
    ports:
      - 16379:16379

  warp10:
    << : *warp10
    environment:
      << : *warp10_env

    ports:
      - 4802:4802
      - 8081:8081
      - 9718:9718

    volumes:
      - /tmp/warp10:/data
      - '${PWD}/warpscript:/usr/local/share/warpscript'
