#!/usr/bin/with-contenv sh

echo 'starting sensision exporter'
./warp10_sensision_exporter --warp10.url=http://localhost:8082/metrics
status=$?
if [ $status -ne 0 ]; 
then
  echo "Failed to start sensision exporter: $status from directory: ${PWD}"
  exit $status
else
  echo "sensision exporter started"
fi