apiVersion: v1
kind: Pod
metadata:
  name: "utapi-test-pod"
spec:
  activeDeadlineSeconds: 3600
  restartPolicy: Never
  terminationGracePeriodSeconds: 10
  containers:
  - name: aggressor
    image: "{{ images.aggressor }}"
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 3Gi
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket
    - name: artifacts
      readOnly: false
      mountPath: /artifacts
  - name: warp10
    image: "{{ images.warp10 }}"
    command:
      - sh
      - -ce
      - /init | tee -a /artifacts/warp10.log
    env:
      - name: standalone.port
        value: '4802'
      - name: warp.token.file
        value: /opt/warp10/etc/ci.tokens
      - name: warpscript.maxops
        value: '10000000'
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1750m
        memory: 3Gi
    volumeMounts:
    - name: artifacts
      readOnly: false
      mountPath: /artifacts
{% if vars.vault is defined and vars.vault == 'enabled' -%}
  - name: vault
    image: "{{ images.vault }}"
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 128Mi
{%- endif %}
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
      type: Socket
  - name: artifacts
    emptyDir: {}
