apiVersion: v1
kind: Pod
metadata:
  name: "utapi-test-pod"
spec:
  activeDeadlineSeconds: 3600
  restartPolicy: Never
  terminationGracePeriodSeconds: 10
  containers:
  - name: aggressor
    image: {{ images.aggressor }}
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "3"
        memory: 3Gi
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-socket
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
      type: Socket
