apiVersion: v1
kind: Pod
metadata:
  name: "utapi-test-pod"
spec:
  activeDeadlineSeconds: 3600
  restartPolicy: Never
  terminationGracePeriodSeconds: 10
  containers:
  - name: aggressor
    image: "{{ images.aggressor }}"
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 500m
        memory: 3Gi
      limits:
        cpu: 1500m
        memory: 3Gi
    volumeMounts:
    - name: artifacts
      readOnly: false
      mountPath: /artifacts
  - name: warp10
    image: "{{ images.warp10 }}"
    command:
      - sh
      - -ce
      - /init | tee -a /artifacts/warp10.log
    env:
      - name: standalone.port
        value: '4802'
      - name: warpscript.maxops
        value: '10000000'
      - name: ENABLE_SENSISION
        value: 't'
    resources:
      requests:
        cpu: 300m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 3Gi
    volumeMounts:
    - name: artifacts
      readOnly: false
      mountPath: /artifacts
  - name: redis
    image: "{{ images.redis }}"
    command:
      - sh
      - -ce
      - /init | tee -a /artifacts/redis.log
    resources:
      requests:
        cpu: 150m
        memory: 500Mi
      limits:
        cpu: 200m
        memory: 500Mi
    volumeMounts:
    - name: artifacts
      readOnly: false
      mountPath: /artifacts
  - name: redis-replica
    image: "{{ images.redis }}"
    command:
      - sh
      - -ce
      - redis-server --port 6380 --slaveof localhost 6379 --slave-announce-ip localhost | tee -a /artifacts/redis.log
    resources:
      requests:
        cpu: 150m
        memory: 500Mi
      limits:
        cpu: 150m
        memory: 500Mi
    volumeMounts:
    - name: artifacts
      readOnly: false
      mountPath: /artifacts
  - name: redis-sentinel
    image: "{{ images.redis }}"
    command:
      - sh
      - -c
      - |-
        cat > /tmp/sentinel.conf <<EOF
        port 16379
        logfile ""
        dir /tmp
        sentinel announce-ip localhost
        sentinel announce-port 16379
        sentinel monitor scality-s3 localhost 6379 1
        EOF
        redis-sentinel /tmp/sentinel.conf
    resources:
      requests:
        cpu: 150m
        memory: 500Mi
      limits:
        cpu: 150m
        memory: 500Mi
    volumeMounts:
    - name: artifacts
      readOnly: false
      mountPath: /artifacts
    ports:
      - containerPort: 16379
{% if vars.vault is defined and vars.vault == 'enabled' %}
  - name: vault
    image: registry.scality.com/vault-dev/vault:c2607856
    command:
      - bash
      - -c
      - 'chmod 400 tests/utils/keyfile && yarn start | tee -a /artifacts/vault.log'
    env:
      - name:  VAULT_DB_BACKEND
        value: LEVELDB
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 1Gi
    volumeMounts:
    - name: artifacts
      readOnly: false
      mountPath: /artifacts
{% endif %}
  volumes:
  - name: artifacts
    emptyDir: {}

