#!/usr/bin/with-contenv sh

export SENSISIONID=warp10
export MALLOC_ARENA_MAX=1

JAVA="/usr/bin/java"
WARP10_JAR=${WARP10_HOME}/bin/warp10-${WARP10_VERSION}.jar
WARP10_CLASS=io.warp10.standalone.Warp
WARP10_CP="${WARP10_HOME}/etc:${WARP10_JAR}:${WARP10_HOME}/lib/*"
WARP10_CONFIG_DIR="$WARP10_DATA_DIR/conf"
CONFIG_FILES="$(find ${WARP10_CONFIG_DIR} -not -path "*/\.*" -name "*.conf" | sort | tr '\n' ' ' 2> /dev/null)"
LOG4J_CONF=${WARP10_HOME}/etc/log4j.properties

if [ -z "$WARP10_HEAP" ]; then
    WARP10_HEAP=1g
fi

if [ -z "$WARP10_HEAP_MAX" ]; then
    WARP10_HEAP_MAX=4g
fi

JAVA_OPTS="-javaagent:/opt/jmx_prom_agent.jar=4803:/opt/jmx_prom_agent.yaml -Djava.awt.headless=true -Xms${WARP10_HEAP} -Xmx${WARP10_HEAP_MAX} -XX:+UseG1GC ${JAVA_OPTS}"

SENSISION_OPTS=
if [ -n "$ENABLE_SENSISION" ]; then
    _SENSISION_LABELS=
    # Expects a comma seperated list of key=value ex key=value,foo=bar
    if [ -n "$SENSISION_LABELS" ]; then
        _SENSISION_LABELS="-Dsensision.default.labels=$SENSISION_LABELS"
    fi
    SENSISION_OPTS="${_SENSISION_LABELS} -Dsensision.events.dir=/var/run/sensision/metrics -Dfile.encoding=UTF-8"
fi

WARP10_CMD="${JAVA} -Dlog4j.configuration=file:${LOG4J_CONF} ${JAVA_OPTS} ${SENSISION_OPTS} -cp ${WARP10_CP} ${WARP10_CLASS} ${CONFIG_FILES}"

echo "Starting Warp 10 with $WARP10_CMD ..."
exec $WARP10_CMD | tee -a ${WARP10_HOME}/logs/warp10.log
