---
version: 0.2

branches:
  default:
    stage: pre-merge

stages:
  pre-merge:
    worker:
      type: local
    steps:
    - TriggerStages:
        name: trigger all the tests
        stage_names:
        - run-tests
  run-tests:
    worker: &workspace
      type: kube_pod
      path: eve/workers/pod.yml
      images:
        aggressor: eve/workers/unit_and_feature_tests
    steps:
      - Git: &git
          name: fetch source
          repourl: '%(prop:git_reference)s'
          shallow: True
          retryFetch: True
          haltOnFailure: True
      - ShellCommand:
          name: npm install
          command: npm install
          haltOnFailure: True
      - ShellCommand:
          name: npm run postinstall
          command: npm run postinstall
      - ShellCommand:
          name: run static analysis tools on markdown
          command: npm run lint_md
      - ShellCommand:
          name: run static analysis tools on code
          command: npm run lint
      - ShellCommand:
          name: run unit tests
          command: npm test
      - ShellCommand:
          name: run feature tests
          command: bash ./eve/workers/unit_and_feature_tests/run_ft_tests.bash ft_test
