---
version: 0.2

branches:
  default:
    stage: pre-merge

models:
  - Git: &clone
      name: Pull repo
      repourl: '%(prop:git_reference)s'
      shallow: True
      retryFetch: True
      haltOnFailure: True
  - Workspace: &workspace
      type: kube_pod
      path: eve/workers/pod.yml
      images:
        aggressor: eve/workers/unit_and_feature_tests
  - Install: &install
      name: install node modules
      command: yarn install --frozen-lockfile
      haltOnFailure: True

stages:
  pre-merge:
    worker:
      type: local
    steps:
    - TriggerStages:
        name: trigger all the tests
        stage_names:
        - linting-coverage
        - run-unit-tests
        - run-client-tests
        - run-server-tests
        - run-cron-tests
        - run-interval-tests
        - run-v2-functional-tests
  linting-coverage:
    worker: *workspace
    steps:
      - Git: *clone
      - ShellCommand: *install
      - ShellCommand:
          name: run static analysis tools on markdown
          command: yarn run lint_md
      - ShellCommand:
          name: run static analysis tools on code
          command: yarn run lint
  run-unit-tests:
    worker: *workspace
    steps:
      - Git: *clone
      - ShellCommand: *install
      - ShellCommand:
          name: run unit tests
          command: yarn test
  run-client-tests:
    worker: *workspace
    steps:
      - Git: *clone
      - ShellCommand: *install
      - ShellCommand:
          name: run client tests
          command: bash ./eve/workers/unit_and_feature_tests/run_ft_tests.bash false ft_test:client
  run-server-tests:
    worker: *workspace
    steps:
      - Git: *clone
      - ShellCommand: *install
      - ShellCommand:
          name: run server tests
          command: bash ./eve/workers/unit_and_feature_tests/run_ft_tests.bash false ft_test:server
  run-cron-tests:
    worker: *workspace
    steps:
      - Git: *clone
      - ShellCommand: *install
      - ShellCommand:
          name: run cron tests
          command: bash ./eve/workers/unit_and_feature_tests/run_ft_tests.bash false ft_test:cron
  run-interval-tests:
    worker: *workspace
    steps:
      - Git: *clone
      - ShellCommand: *install
      - ShellCommand:
          name: run interval tests
          command: bash ./eve/workers/unit_and_feature_tests/run_ft_tests.bash true ft_test:interval
  run-v2-functional-tests:
    worker: *workspace
    steps:
      - Git: *clone
      - ShellCommand: *install
      - ShellCommand:
          name: run v2 functional tests
          command: SETUP_CMD=start_v2:server bash ./eve/workers/unit_and_feature_tests/run_ft_tests.bash true ft_test:interval
