name: build-ci-images

on:
  workflow_call:

jobs:
  warp10-ci:
    uses: scality/workflows/.github/workflows/docker-build.yaml@v2
    secrets:
      REGISTRY_LOGIN: ${{ github.repository_owner }}
      REGISTRY_PASSWORD: ${{ github.token }}
    with:
      name: warp10-ci
      context: .
      file: images/warp10/Dockerfile
      lfs: true

  redis-ci:
    uses: scality/workflows/.github/workflows/docker-build.yaml@v2
    secrets:
      REGISTRY_LOGIN: ${{ github.repository_owner }}
      REGISTRY_PASSWORD: ${{ github.token }}
    with:
      name: redis-ci
      context: .
      file: images/redis/Dockerfile

  redis-replica-ci:
    uses: scality/workflows/.github/workflows/docker-build.yaml@v2
    needs:
      - redis-ci
    secrets:
      REGISTRY_LOGIN: ${{ github.repository_owner }}
      REGISTRY_PASSWORD: ${{ github.token }}
    with:
      name: redis-replica-ci
      context: .github/docker/redis-replica
      build-args: |
        REDIS_IMAGE=ghcr.io/${{ github.repository }}/redis-ci:${{ github.sha }}

  vault-ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push vault Image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .github/docker/vault
          tags: ghcr.io/${{ github.repository }}/vault-ci:${{ github.sha }}
          cache-from: type=gha,scope=vault
          cache-to: type=gha,mode=max,scope=vault
