name: release-warp10

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'Tag to be released'
        required: true
      create-github-release:
        type: boolean
        description: Create a tag and matching Github release.
        required: false
        default: true

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: scality/workflows/.github/workflows/docker-build.yaml@v2
    with:
      name: warp10
      context: .
      file: images/warp10/Dockerfile
      tag: ${{ inputs.tag }}
      lfs: true

  release:
    if: ${{ inputs.create-github-release }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Github Release for Warp10
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release utapi/warp10:${{ github.event.inputs.tag }}-warp10
          target_commitish: ${{ github.sha }}
          tag_name: ${{ github.event.inputs.tag }}-warp10
          generate_release_notes: false
